Repository werf/werf, pull requests merged in 2021-11, with the labels that each got.

#3900 chore: release 1.2.38
  CHANGELOG.md
Labels: autorelease: pending

#3904 chore: release 1.2.39
  CHANGELOG.md
Labels: autorelease: pending

#3909 site: Tune google search, highlight documentation version, remove guide's banner
  docs/site/_includes/group-menu.html
  docs/site/js/customscripts.js
  docs/site/pages_en/guides.md
  docs/site/pages_ru/guides.md
Labels: test docs

#3918 chore: release 1.2.40
  CHANGELOG.md
Labels: autorelease: pending

#3930 chore: release 1.2.41
  CHANGELOG.md
Labels: autorelease: pending

#3845 feat: werf installation script for linux/macos
  docs/documentation/werf.yaml
  docs/site/_includes/en/installation/binary_linux.md
  docs/site/_includes/en/installation/binary_macos.md
  docs/site/_includes/en/installation/binary_windows.md
  docs/site/_includes/en/installation/installer_linux_macos.md
  docs/site/_includes/en/installation/installer_windows.md
  docs/site/_includes/ru/installation/binary_linux.md
  docs/site/_includes/ru/installation/binary_macos.md
  docs/site/_includes/ru/installation/binary_windows.md
  docs/site/_includes/ru/installation/installer_linux_macos.md
  docs/site/_includes/ru/installation/installer_windows.md
  docs/site/pages_en/installation.md
  docs/site/pages_ru/installation.md
  scripts/install.sh
Labels: type: enhancement, review docs, test docs, scope: documentation

#3944 chore: release 1.2.42
  CHANGELOG.md
Labels: autorelease: pending

#3947 infra: serve werf and kubedog public PGP keys
  docs/documentation/werf.yaml
  docs/site/install.sh
  docs/site/kubedog.asc
  docs/site/werf.asc
Labels: test docs

#3954 chore: release 1.2.43
  CHANGELOG.md
Labels: autorelease: pending

#3955 chore: release 1.2.44
  CHANGELOG.md
Labels: autorelease: pending

#3971 docs: 1.2 stable
  docs/documentation/pages_en/advanced/ci_cd/gitlab_ci_cd.md
  docs/documentation/pages_en/advanced/cleanup.md
  docs/documentation/pages_ru/advanced/ci_cd/gitlab_ci_cd.md
  docs/documentation/pages_ru/advanced/cleanup.md
  docs/site/.helm/trdl_channels-dev.yaml
  docs/site/js/installation.js
Labels: test docs
