Repository werf/werf, pull requests merged in 2021-12, with the labels that each got.

#3975 docs(buildah): added advanced/ci-cd docs about werf usage in containers and kubernetes
  docs/documentation/_data/breadcrumbs.yml
  docs/documentation/_data/sidebars/_documentation.yml
  docs/documentation/_data/sidebars/documentation.yml
  docs/documentation/pages_en/advanced/ci_cd/werf_in_container/use_docker.md
  docs/documentation/pages_en/advanced/ci_cd/werf_in_container/use_docker_for_github_actions.md
  docs/documentation/pages_en/advanced/ci_cd/werf_in_container/use_docker_for_gitlab_ci_cd.md
  docs/documentation/pages_en/advanced/ci_cd/werf_in_container/use_kubernetes.md
  docs/documentation/pages_en/advanced/ci_cd/werf_in_container/use_kubernetes_for_github_actions.md
  docs/documentation/pages_en/advanced/ci_cd/werf_in_container/use_kubernetes_for_gitlab_ci_cd.md
Labels: review docs

#3976 chore: release 1.2.45
  CHANGELOG.md
Labels: autorelease: pending

#3981 chore: release 1.2.47
  CHANGELOG.md
Labels: autorelease: pending

#3992 chore: release 1.2.48
  CHANGELOG.md
Labels: autorelease: pending

#4004 chore: release 1.2.49
  CHANGELOG.md
Labels: autorelease: pending

#4011 chore: release 1.2.50
  CHANGELOG.md
Labels: autorelease: pending

#4017 chore: release 1.2.51
  CHANGELOG.md
Labels: autorelease: pending

#4034 chore: release 1.2.52
  CHANGELOG.md
Labels: autorelease: pending

#4038 chore: release 1.1.28
  CHANGELOG.md
Labels: autorelease: pending

#4041 chore: release 1.2.53
  CHANGELOG.md
Labels: autorelease: pending

#4043 docs: Buildah articles & run in container
  docs/pages_en/advanced/buildah_mode.md
  docs/pages_en/advanced/ci_cd/run_in_container/how_it_works.md
  docs/pages_en/advanced/ci_cd/run_in_container/use_docker_container.md
  docs/pages_en/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_docker_executor.md
  docs/pages_en/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.md
  docs/pages_en/advanced/ci_cd/run_in_container/use_kubernetes.md
  docs/pages_en/internals/build_process.md
  docs/pages_ru/advanced/buildah_mode.md
  docs/pages_ru/advanced/ci_cd/run_in_container/how_it_works.md
  docs/pages_ru/advanced/ci_cd/run_in_container/use_docker_container.md
  docs/pages_ru/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_docker_executor.md
  docs/pages_ru/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.md
  docs/pages_ru/advanced/ci_cd/run_in_container/use_kubernetes.md
  docs/pages_ru/internals/build_process.md
Labels: scope: documentation

#4047 chore: release 1.2.54
  CHANGELOG.md
Labels: autorelease: pending

#4055 chore: release 1.2.55
  CHANGELOG.md
Labels: autorelease: pending
