Repository werf/werf, pull requests merged in 2022-04, with the labels that each got.

#4312 chore: release 1.2.81
  CHANGELOG.md
Labels: autorelease: pending

#4325 chore: release 1.2.82
  CHANGELOG.md
Labels: autorelease: pending

#4328 chore: release 1.2.83
  CHANGELOG.md
Labels: autorelease: pending

#4335 chore: release 1.2.84
  CHANGELOG.md
Labels: autorelease: pending

#4341 chore: release 1.2.85
  CHANGELOG.md
Labels: autorelease: pending

#4353 chore: release 1.2.86
  CHANGELOG.md
Labels: autorelease: pending

#4357 chore: release 1.2.87
  CHANGELOG.md
Labels: autorelease: pending

#4369 refactor(container_backend): support all dep imports parameters
  pkg/container_backend/buildah_backend.go
Labels: run tests

#4359 chore: release 1.2.88
  CHANGELOG.md
Labels: autorelease: pending

#4381 chore: release 1.2.89
  CHANGELOG.md
Labels: autorelease: pending

#4384 chore: release 1.2.90
  CHANGELOG.md
Labels: autorelease: pending

#4393 chore: release 1.2.91
  CHANGELOG.md
Labels: autorelease: pending

#4388 docs: add notice about the language of the CLI pages
  docs/_config.yml
  docs/_includes/no-language-warning.html
  docs/_layouts/page.html
Labels: test docs, scope: documentation

#4401 chore: release 1.2.92
  CHANGELOG.md
Labels: autorelease: pending

#4407 chore: release 1.2.93
  CHANGELOG.md
Labels: autorelease: pending

#4413 chore: release 1.2.94
  CHANGELOG.md
Labels: autorelease: pending
