Repository werf/werf, pull requests merged in 2022-07, with the labels that each got.

#4574 chore: release 1.2.119
  CHANGELOG.md
Labels: autorelease: pending

#4580 chore: release 1.2.120
  CHANGELOG.md
Labels: autorelease: pending

#4583 chore: release 1.2.121
  CHANGELOG.md
Labels: autorelease: pending

#4590 chore: release 1.2.122
  CHANGELOG.md
Labels: autorelease: pending

#4605 chore: release 1.2.124
  CHANGELOG.md
Labels: autorelease: pending

#4609 chore: release 1.2.125
  CHANGELOG.md
Labels: autorelease: pending

#4596 docs: external dependencies and resource weight
  docs/_data/sidebars/_documentation.yml
  docs/_data/sidebars/documentation.yml
  docs/_includes/reference/cli/werf_kubectl_get.md
  docs/pages_en/advanced/helm/deploy_process/external_dependencies.md
  docs/pages_en/advanced/helm/deploy_process/resource_order.md
  docs/pages_en/advanced/helm/deploy_process/steps.md
  docs/pages_en/reference/deploy_annotations.md
Labels: test docs

#4623 chore: release 1.2.129
  CHANGELOG.md
Labels: autorelease: pending

#4628 chore: release 1.2.130
  CHANGELOG.md
Labels: autorelease: pending

#4630 chore: release 1.2.131
  CHANGELOG.md
Labels: autorelease: pending

#4632 chore: release 1.2.132
  CHANGELOG.md
Labels: autorelease: pending

#4635 docs(helm): `werf.io/no-activity-timeout` annotation
  docs/pages_en/reference/deploy_annotations.md
  docs/pages_ru/reference/deploy_annotations.md
Labels: test docs

#4641 chore: release 1.2.133
  CHANGELOG.md
Labels: autorelease: pending

#4647 chore: release 1.2.135
  CHANGELOG.md
Labels: autorelease: pending

#4650 chore: release 1.2.136
  CHANGELOG.md
Labels: autorelease: pending

#4654 chore: release 1.2.137
  CHANGELOG.md
Labels: autorelease: pending

#4658 chore: release 1.2.138
  CHANGELOG.md
Labels: autorelease: pending

#4661 chore: release 1.2.139
  CHANGELOG.md
Labels: autorelease: pending

#4665 docs: Translate telemetry.md
  docs/pages_en/internals/telemetry.md
Labels: scope: documentation

#4667 chore: release 1.2.140
  CHANGELOG.md
Labels: autorelease: pending

#4673 chore: release 1.2.141
  CHANGELOG.md
Labels: autorelease: pending

#4677 chore: release 1.2.142
  CHANGELOG.md
Labels: autorelease: pending

#4683 chore: release 1.2.143
  CHANGELOG.md
Labels: autorelease: pending

#4685 chore: release 1.2.144
  CHANGELOG.md
Labels: autorelease: pending
