Repository werf/werf, pull requests merged in 2023-02, with the labels that each got.

#5302 fix(build): TOOMANYREQUESTS error occurs for the built images
  pkg/build/image/image.go
Labels: trigger: test:main

#5313 chore: release 1.2.201
  CHANGELOG.md
Labels: autorelease: pending

#5300 Expanded parent items
  docs/_includes/sidebar.html
  docs/_includes/sidebar_entry.html
  docs/_layouts/default.html
Labels: trigger: docs:deploy:pr

#5318 chore: release 1.2.202
  CHANGELOG.md
Labels: autorelease: pending

#5328 chore: release 1.2.203
  CHANGELOG.md
Labels: autorelease: pending

#5339 chore: release 1.2.204
  CHANGELOG.md
Labels: autorelease: pending
