Repository werf/werf, pull requests merged in 2024-12, with the labels that each got.

#6452 chore: release 2.15.0
  CHANGELOG.md
Labels: autorelease: pending

#6449 chore: release 1.2.332
  CHANGELOG.md
Labels: autorelease: pending

#6460 chore: release 2.15.1
  CHANGELOG.md
Labels: autorelease: pending

#6462 chore: release 2.15.2
  CHANGELOG.md
Labels: autorelease: pending

#6467 chore(ci): remove deploy test docs
  .github/workflows/docs_deploy_latest.yml
  .github/workflows/docs_deploy_tag.yml
Labels: trigger: docs:deploy:pr

#6469 chore: release 2.16.0
  CHANGELOG.md
Labels: autorelease: pending

#6476 chore: release 1.2.333
  CHANGELOG.md
Labels: autorelease: pending

#6473 chore: release 2.16.1
  CHANGELOG.md
Labels: autorelease: pending

#6482 chore(site): fix tls key
  docs/.helm/templates/20-ingress.yaml
Labels: trigger: test:main, trigger: docs:deploy:pr

#6479 chore: release 2.16.2
  CHANGELOG.md
Labels: autorelease: pending

#6477 fix(build): fix data races
  pkg/build/conveyor.go
  pkg/docker_registry/docker_registry_with_cache.go
  pkg/true_git/git_cmd.go
  pkg/true_git/service_branch.go
  pkg/util/goroutine_safe_buffer.go
Labels: trigger: docs:deploy:pr

#6489 refactor(build): remove ssh sock from conveyor and add default agent
  cmd/werf/build/main.go
  cmd/werf/bundle/publish/publish.go
  cmd/werf/compose/main.go
  cmd/werf/converge/converge.go
  cmd/werf/export/export.go
  cmd/werf/helm/get_autogenerated_values.go
  cmd/werf/kube_run/kube_run.go
  cmd/werf/plan/plan.go
  cmd/werf/render/render.go
  cmd/werf/run/run.go
  cmd/werf/stage/image/main.go
  docs/_data/werf_yaml.yml
  docs/pages_en/usage/build/images.md
  docs/pages_en/usage/build/process.md
  docs/pages_en/usage/build/stapel/git.md
  docs/pages_en/usage/build/stapel/instructions.md
  docs/pages_ru/usage/build/images.md
  docs/pages_ru/usage/build/process.md
  docs/pages_ru/usage/build/stapel/git.md
  docs/pages_ru/usage/build/stapel/instructions.md
  integration/suites/build/secrets/_fixtures/build_with_secrets/Dockerfile
  integration/suites/build/secrets/_fixtures/build_with_secrets/file
  integration/suites/build/secrets/_fixtures/build_with_secrets/werf-giterminism.yaml
  integration/suites/build/secrets/_fixtures/build_with_secrets/werf.yaml
  integration/suites/build/secrets/_fixtures/build_with_ssh/Dockerfile
  integration/suites/build/secrets/_fixtures/build_with_ssh/file
  integration/suites/build/secrets/_fixtures/build_with_ssh/werf.yaml
  integration/suites/build/secrets/secrets_test.go
  integration/suites/build/secrets/suite_test.go
  pkg/build/build_phase.go
  pkg/build/builder/ansible.go
  pkg/build/builder/shell.go
  pkg/build/conveyor.go
  pkg/build/conveyor_with_retry.go
  pkg/build/image/dockerfile.go
  pkg/build/stage/instruction/run.go
  pkg/build/stage/user.go
  pkg/buildah/common.go
  pkg/buildah/native_linux.go
  pkg/container_backend/build_stapel_stage_options.go
  pkg/container_backend/buildah_backend.go
  pkg/container_backend/docker_server_backend.go
  pkg/container_backend/instruction/run.go
  pkg/container_backend/legacy_interface.go
  pkg/container_backend/legacy_stage_image_builder_container.go
  pkg/container_backend/utils.go
  pkg/ssh_agent/ssh_agent.go
Labels: trigger: docs:deploy:pr

#6498 chore(ci): fix docs validate test
  docs/pages_en/usage/build/stapel/instructions.md
  docs/pages_ru/usage/build/stapel/instructions.md
Labels: trigger: docs:deploy:pr

#6488 chore: release 2.16.3
  CHANGELOG.md
Labels: autorelease: pending

#6504 chore: release 2.17.0
  CHANGELOG.md
Labels: autorelease: pending

#6523 chore(docs): increase the priority of usage pages
  docs/sitemap.xml
Labels: trigger: docs:deploy:pr

#6491 chore(docs): add backend doc
  docs/_data/sidebars/_documentation.yml
  docs/_data/sidebars/documentation.yml
  docs/pages_en/reference/werf_images.md
  docs/pages_en/usage/build/backends.md
  docs/pages_ru/reference/werf_images.md
  docs/pages_ru/usage/build/backends.md
Labels: trigger: docs:deploy:pr
